version: "3.5"

services:
    rabbitmq:
        container_name: rabbitmq
        image: masstransit/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - falc-local
        
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data/pgdata
        hostname: postgres
        volumes:
            - ./postgres-data/:/var/lib/postgresql
        networks:
            - falc-local
              
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak
        ports:
            - "8080:8080"
        environment:
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_DATABASE: postgres
            DB_USER: postgres
            DB_PASSWORD: password
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
        command:
            - start-dev
        networks:
            - falc-local
        depends_on:
            - postgres

    ngrok:
        container_name: ngrok
        image: ngrok/ngrok
        ports:
            - "4040:4040"
        command:
            - "start"
            - "cronofy.api"
            - "--config"
            - "/etc/ngrok.yml"
        volumes:
            - ./ngrok.yml:/etc/ngrok.yml
        networks: 
            - falc-local

networks:
    falc-local:
        external: true